# Generated by Django 5.1.4 on 2024-12-30 22:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
