# Generated by Django 5.1.4 on 2024-12-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_servicepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='body',
            new_name='description',
        ),
    ]
